export const communityMembers = [
  { blockstackId: 'larry',
    name: 'Larry Salibra',
    avatar: 'https://s3.amazonaws.com/kd4/larry',
    twitter: 'larrysalibra',
    github: 'larrysalibra' },
  { blockstackId: 'judecn',
    name: 'Jude Nelson',
    avatar: 'https://s3.amazonaws.com/kd4/judecn',
    twitter: 'judecnelson',
    github: 'jcnelson' },
  { blockstackId: 'guylepage3',
    name: 'Guy Lepage',
    avatar: 'https://s3.amazonaws.com/kd4/guylepage3',
    twitter: 'guylepage3',
    github: 'guylepage3' },
  { blockstackId: 'muneeb',
    name: 'Muneeb Ali',
    avatar: 'https://s3.amazonaws.com/kd4/muneeb',
    twitter: 'muneeb',
    github: 'muneeb-ali' },
  { blockstackId: 'ryan',
    name: 'Ryan Shea',
    avatar: 'https://s3.amazonaws.com/kd4/ryan',
    twitter: 'ryaneshea',
    github: 'shea256' },
  { blockstackId: 'starkness',
    name: 'Elizabeth Stark',
    avatar: 'https://s3.amazonaws.com/kd4/starkness',
    twitter: 'starkness',
    github: 'starkness' },
  { blockstackId: 'lightcoin',
    name: 'John Light',
    avatar: 'https://s3.amazonaws.com/kd4/lightcoin',
    twitter: 'lightcoin',
    github: 'john-light' },
  { blockstackId: 'itsprof',
    name: 'Jorge Tapia',
    avatar: 'https://s3.amazonaws.com/kd4/itsprof',
    twitter: 'itsprof',
    github: 'itsprof' },
  { blockstackId: 'buchner',
    name: 'Daniel Buchner',
    avatar: 'https://s3.amazonaws.com/kd4/buchner',
    twitter: 'csuwildcat',
    github: 'csuwildcat' },
  { blockstackId: 'mfreed',
    name: 'Michael Freedman',
    avatar: '/images/avatars/mike-freedman.jpg',
    twitter: 'michaelfreedman',
    github: 'mfreed' },
  { blockstackId: 'becky_',
    name: 'Becky Berry',
    avatar: 'https://s3.amazonaws.com/kd4/becky_',
    facebook: 'becky.berry.104' },
]